FROM node:14 as build

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/public ./public
COPY frontend/src ./src

RUN npm run build

FROM node:14-alpine
WORKDIR /app
COPY --from=build /app/build ./build
COPY frontend/package*.json ./
RUN npm install --production

CMD ["npm", "start"]