version: '3.8'

services:
  frontend:
    build:
      context: ./docker
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - nginx

  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - frontend